Add Scale harmonization feature
gciruelos/musthe pull request #29
Opened 2024-07-18 13:31 UTC by mystery-house

This pull request adds two new methods to the `Scale` class, `harmonize()` and `harmonize_dict()`. 

Each one calculates a list of diatonic chords per note in the scale, plus dominant 7th chords.

Dominant 7th chords are included by default, but can be omitted with an argument.

`harmonize()` returns a list of lists, where the outer index corresponds to the index of each note in the scale. `harmonize_dict()` returns a dict of lists, where the dict keys correspond to note names. For examples, see the JSON files in the `tests` directory.

Also included are two example scripts which can be used to update the test JSON files if new scale or chord recipes are added in the future.

2024-07-19 15:04 UTC, gciruelos requested changes
thank you for the contribution! It looks good, please resolve the comments and I will merge it.

2024-07-19 15:04 UTC, gciruelos commented on tests/harmonized_scales_list.json
do we really need 8k lines of tests? can you please reduce this to at most 200 lines testing some representative examples?

2024-07-19 19:08 UTC, gciruelos commented on tests/harmonized_scales_list.json
looking at them more closely, i think something around 40-50 lines per json file should be enough

2024-07-20 14:36 UTC, mystery-house commented on tests/harmonized_scales_list.json
Yep. I erred on the side of completeness, but I'll scale it back.

2024-07-24 14:16 UTC, mystery-house commented on musthe/musthe.py
> +        chords = [None]*len(self.notes)
Done.

2024-07-24 14:19 UTC, mystery-house commented on tests/harmonized_scales_list.json
I removed the large JSON files in favor of tests for `harmonize()` and `harmonize_dict()` with and without the `include_dom7` flag; each one tests a different scale, and it tests the expected `None` result when no chords can be matched, so it should be pretty representative.

2024-07-29 17:33 UTC, merged

2024-07-29 17:34 UTC, gciruelos commented
Merged, thank you for your contribution.